### ISSUE TITLE
Benchmarking Mongodb 3.0

### ISSUE THREAD

**Issue by smileisak** [mongodb/mongo-perf#36]
I'm trying to make benchmarking in mongodb repilca set with 3 instances, but when i try to lunch the script 

```
 python benchrun.py -f test.js --mongo-repo-path tests  -t 1 2 4 8 16 -l mytest
```

it shows me

```
MongoDB shell version: 3.0.0
connecting to: 127.0.0.1:27017/test
db version: 3.0.0
nogitversion

Warning: could not find Git commit nogitversion in main mongodb repo. Error: 
WARNING: setting git commit date to current date and time
load('util/utils.js')

load('test.js')

mongoPerfRunTests([1, 2, 4, 8, 16], 1, 1, 5, 1, 'mytest', 'sanity', 'localhost', '27017', '2015-03-23 13:27:14.649294', 0, {"writeCmdMode": "true", "writeConcernW": 0, "safeGLE": "false", "writeConcernJ": "false"}, {"server_git_hash": "nogitversion", "server_storage_engine": "mmapv1", "harness": {"git_hash": "unknown", "client": {"git_hash": "nogitversion", "version": "3.0.0", "name": "mongo shell"}, "name": "mongo-perf", "version": "unknown"}, "server_git_commit_date": "2015-03-23 13:27:14.478991", "server_version": "3.0.0", "topology": "single_node"});

2015-03-23T13:27:14.662+0100 E QUERY    ReferenceError: tests is not defined
at runTests (util/utils.js:409:25)
at mongoPerfRunTests (util/utils.js:503:19)
at (shell):1:1 at util/utils.js:409
Finished Testing.

```

content of test.js:

```
for (var i = 1; i <= 25; i++) {
   db.testData.insert( { x : i } )
}
```

**Comment by dalyd** [comment]
Hi smileisak. Try with the latest master. There are a couple changes fixing a bug with remote hosts that hopefully fixes this.

**Comment by neekfenwick** [comment]
I'm getting this too, with the latest master, because my default javascript development pattern uses `jshint` and it works best if I add `'use strict';` at the top of the files to quieten down its output.  Unfortunately this means the undeclared global `tests` variable in the default scripts that I copied (`simple_query.js`) doesn't compile, throwing the error `tests is not defined`.

I just removed my `use strict` and mongo-perf ran successfully.

I'm finding the documentation extremely brief, though, I hope this effort leads somewhere and I don't end up throwing it out due to not knowing how to use its results.

**Comment by dalyd** [comment]
Hi neekfenwich. I'm not sure I follow. At the top of simple_query.js is 
if ( typeof(tests) != "object" ) {
    tests = [];
}

which defines tests as an empty array if it doesn't already exist. Are you getting an error because there is no "var tests" showing up in the file?
