### ISSUE TITLE
--authenticationDatabase should be hard-coded in benchrun.py

### ISSUE THREAD

**Issue by sleonov** [mongodb/mongo-perf#48]
I had to modify this code section to change admin to test:

    if args.username:
        auth = ["-u", args.username, "-p", args.password, "--authenticationDatabase", "test"]
    else:
        auth = []

**Comment by henrikingo** [comment]
Hi @sleonov 

At least when we added authentication support to benchrun.py, the only way it would actually work is to authenticate with admin rights to the admin database. This is because benchRun (the command in mongo shell) will check that it has admin rights. I'm not quite sure why it does that, I suspect it is due to some historical requirement, but either way, without authenticating against admin db, it didn't work. I'm also pretty sure it didn't change in the mean time.

I don't remember the exact error that happened here, but note that in many cases benchRun will silently ignore errors. So in this case it would fail to connect, but to the user everything would look fine. The only clue that it's failing is that the results reported are much higher than normally, because the test isn't actually doing anything due to the authentication error.
