### ISSUE TITLE
How to interpret the results

### ISSUE THREAD

**Issue by kamal2222ahmed** [mongodb/mongo-perf#50]
How do i interpret the results:

Update.SetWithIndex.Random
1	6479.256421669252
2	11962.410365902673
4	11498.471975148554
Insert.JustID
1	8823.753188457655
2	16186.889606186704
4	22600.29665101042
MultiUpdate.Uncontended.SingleDoc.Indexed
1	6468.106769801784
2	11771.81590510325
4	11304.288194020975
MultiUpdate.Uncontended.TwoDocs.NoIndex
1	5487.364794184829
2	9724.114674670303
4	8904.604674237715
MultiUpdate.Uncontended.TwoDocs.Indexed
1	4544.113018652349
2	7725.084605117798
4	6684.985108602144
MultiUpdate.Contended.Low.NoIndex
1	7157.487622865289
2	13623.688896527088
4	15691.345983427876
MultiUpdate.Contended.Low.Indexed
1	6431.6207272327365
2	11920.198494019205
4	11193.747495326525
Update.IncWithIndex
1	6472.556619873768
2	12000.153161112394
4	11539.943671264098
Update.IncNoIndexUpsert
1	7437.99190614989
2	13676.18368931441
4	15640.302042099924
Update.IncWithIndexUpsert
1	6600.365740524583
2	12291.515620007462
4	11746.803323687693
Update.IncFewSmallDoc
1	6746.105737579126
2	12771.760321043592
4	13769.94419708347
Update.MmsIncShallow2
1	7577.580646951206
2	13638.035496642979
4	15385.744185762896
Update.MmsIncDeep1
1	7516.296022428814
2	13444.671608739773
4	14216.323386495229
Update.MmsIncDeepSharedPath2
1	7191.7674687845865
2	12850.390438559289
4	13147.313224094101
Update.MmsIncDeepSharedPath3
1	6824.148188701889
2	12773.11183128691
4	12637.086700690772

and what are the units , and how can i improve the performance

**Comment by henrikingo** [comment]
Hi Kamal

Each string is the name of a test. What a test does is documented in the test source codes, in testcases/ directory. Example: https://github.com/mongodb/mongo-perf/blob/master/testcases/complex_insert.js#L6-L12

The first number is the number of client threads. The second is the test result, usually either operations / second or documents / second. (You can change the nr of threads, test runtime, etc with options to benchrun.py.)

Note that these mongo-perf tests are so called microbenchmarks. They test some specific operation, like a simple find query. However, they're probably not very relevant in estimating how your MongoDB system would perform with a real-world, larger database.

They are also quite sensitive to random noise. So you might find that there's a lot of variability in your test results. This would be especially the case if you run these tests on a laptop or in a cloud (like EC2). Also on physical server hardware, we turn off several things in order to reduce variance:
* we turn off hyperthreading, CPU sleep states and power saving states and use numactl to pin mongod to a single socket.
* we turn of a lot of background processes in mongod itself, including journaling and logging, so that there's no disk IO during the test.

Now, for your question how to improve the performance.

Like I said, these microbenchmarks are mostly useful as regression tests when developing mongod itself. You could of course try to tweak different mongodb options, or use different hardware, and expect to get different results. But like I said, this is probably not very relevant from the point of view of running a production MongoDB server.

The other answer therefore is that you can use these tests to start hacking on mongod itself, and try to think of ways to try to make it go faster, and then see what results you get. This is of course not easy, and probably not what you were asking about, but it is the answer to your question.

**Comment by assj** [comment]
Hi Henrik.
Do you know what type of operations are being counted for the "total_ops" result?

**Comment by henrikingo** [comment]
It depends on the test. The tests are commented, hopefully that helps.

**Comment by assj** [comment]
> It depends on the test. The tests are commented, hopefully that helps.

You say in the test files? I do not found it there.
In my case is a simple "find" query.

**Comment by henrikingo** [comment]
Oh, seems I was wrong. For these tests it is always total ops per second. The results are collected here: https://github.com/mongodb/mongo-perf/blob/92e7f35e64340128f69ee9f10b96b87752f2c1be/util/utils.js#L391

**Comment by thy143** [comment]
@henrikedin Is there any reference benchmarks to compare my results to? New to mongo but need to set it up for production use so would like to have some benchmarks to compare to. Thanks

**Comment by henrikingo** [comment]
Hi @thy143 

For production servers, I recommend using these benchmarks:
https://github.com/mongodb-labs/YCSB
https://github.com/mongodb-labs/py-tpcc

henrik
